
ALTER TABLE public.tours
  ADD COLUMN IF NOT EXISTS capacidade_max INTEGER,
  ADD COLUMN IF NOT EXISTS duracao TEXT,
  ADD COLUMN IF NOT EXISTS horario TEXT,
  ADD COLUMN IF NOT EXISTS local_saida TEXT,
  ADD COLUMN IF NOT EXISTS info_adicional TEXT,
  ADD COLUMN IF NOT EXISTS observacoes TEXT;
